{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "6fc9a0ed_2605820b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1016895
      },
      "writtenOn": "2022-07-21T10:47:59Z",
      "side": 1,
      "message": "recheck",
      "revId": "04144bf87eb7c3eb45ae1941ef678dfe60cc6ac0",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c1d8bf67_3184badc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2022-07-22T15:21:51Z",
      "side": 1,
      "message": "Ansible still can not retry async tasks? That\u0027s unfortunate...\n\nI just wonder, what issue triggered this? Is there JIRA with the background?",
      "revId": "04144bf87eb7c3eb45ae1941ef678dfe60cc6ac0",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}