{
  "comments": [
    {
      "key": {
        "uuid": "85472d78_66fdc3a4",
        "filename": "infrared/core/services/workspaces.py",
        "patchSetId": 3
      },
      "lineNbr": 333,
      "author": {
        "id": 1001189
      },
      "writtenOn": "2018-04-20T08:12:46Z",
      "side": 1,
      "message": "would recommend to resolve activate path\u0027s real name just once, not in loop inside comprehension please",
      "revId": "066c00aae6fd4b4363a6ec7d51adfd9631747e43",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8befc87c_4eff0d2e",
        "filename": "infrared/core/utils/exceptions.py",
        "patchSetId": 3
      },
      "lineNbr": 136,
      "author": {
        "id": 1001189
      },
      "writtenOn": "2018-04-20T08:12:46Z",
      "side": 1,
      "message": "maybe bit more explanatory about what the issue is ...\n\nWorkspace ... file or folder with name \u0027active\u0027, expected is symlink\n// or\n... \u0027active\u0027 while it should be symlink\n// or\n... something else, to explain what is wrong about \u0027file or folder\u0027 part",
      "revId": "066c00aae6fd4b4363a6ec7d51adfd9631747e43",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}