{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2109aa77_4016306b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1006992
      },
      "writtenOn": "2022-02-14T14:50:37Z",
      "side": 1,
      "message": "Please do not merge this until the following link indicates that the change ID below is in the compose.\n\nhttps://wimp.usersys.redhat.com/?change_id_input\u003dI24bea131cc949888518994a3aa08c200d579cb7d",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "45efd297_f99938fa",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1006992
      },
      "writtenOn": "2022-02-23T18:12:38Z",
      "side": 1,
      "message": "17 compose has the depends-on patch in trunk now\n\nhttps://wimp.usersys.redhat.com/?change_id_input\u003dI24bea131cc949888518994a3aa08c200d579cb7d",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "628bebd9_0387518d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1006992
      },
      "writtenOn": "2022-02-23T18:16:04Z",
      "side": 1,
      "message": "17 compose does NOT have the depends-on patch in trunk.",
      "parentUuid": "45efd297_f99938fa",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8ed1f5ea_df99d3d4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1006992
      },
      "writtenOn": "2022-02-23T18:16:04Z",
      "side": 1,
      "message": "https://wimp.usersys.redhat.com/?change_id_input\u003dI24bea131cc949888518994a3aa08c200d579cb7d",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "35fc49d8_c150c7dc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1006992
      },
      "writtenOn": "2022-03-08T18:35:37Z",
      "side": 1,
      "message": "This the patch needed to test this patch is in the 17 compse:\n\n https://brewweb.engineering.redhat.com/brew/buildinfo?buildID\u003d1889397",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6973a52c_9dc5c72b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1006992
      },
      "writtenOn": "2022-03-11T22:04:35Z",
      "side": 1,
      "message": "The build failed [1] with this:\n\nerror pinging docker registry registry-proxy.engineering.redhat.com: Get \\\"https://registry-proxy.engineering.redhat.com/v2/\\\": x509: certificate signed by unknown authority\n\nI see push_destination is true [2] and that containers were pushed to the undercloud [3]. Assuming the fixes are in the compose, then the new playbooks [4] should have updated /etc/hosts [5] and the container registry [6] but they were not updated.\n\nThe plays \"Configure overcloud container registry\" and \"Configure overcloud hosts file\" are not in the ansible log [3]. They would have been called by the new python client [7][8].\n\nWere the required changes in the compose when this ran? Checking RPMs on undercloud [9].\n\n2022-03-11T15:23:27-0500 SUBDEBUG Installed: tripleo-ansible-3.3.1-0.20220204021043.c195ba1.el8ost.noarch\n\n2022-03-11T15:23:33-0500 SUBDEBUG Installed: python3-tripleoclient-16.4.1-0.20220204020916.6c76392.el8ost.noarch\n\nNext: Need to update here if the fixes were actually tested.\n\n\n[1] http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/208/undercloud-0/home/stack/overcloud_ceph_deployment.log.gz\n\n[2] http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/208/undercloud-0/home/stack/containers-prepare-parameter.yaml.gz\n\n[3] http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/208/undercloud-0/home/stack/ansible.log.gz\n\n[4] https://review.opendev.org/c/openstack/tripleo-ansible/+/828562\n\n[5] http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/208/controller-0/etc/hosts.gz\n\n[6] http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/208/controller-0/etc/containers/registries.conf.gz\n\n[7] https://review.opendev.org/c/openstack/python-tripleoclient/+/828561/3/tripleoclient/v2/overcloud_ceph.py#406\n\n[8] https://review.opendev.org/c/openstack/python-tripleoclient/+/828561/3/tripleoclient/v2/overcloud_ceph.py#447\n\n[9] http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/208/undercloud-0/var/log/dnf.rpm.log.gz",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "10e46b11_f9862ed8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1010634
      },
      "writtenOn": "2022-03-11T23:38:13Z",
      "side": 1,
      "message": "the gate job is using old compose, that\u0027s correct\njust retriggered gate job with latest one",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "1097bd43_2b0446ec",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1010634
      },
      "writtenOn": "2022-03-11T23:40:05Z",
      "side": 1,
      "message": "merging and will test the phase1 and gate jobs with it then... we need this in either form - if ain\u0027t working like this then some making some follow ups ",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "55930d95_7858dc8a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2022-03-14T11:15:36Z",
      "side": 1,
      "message": "I think this might be merged too quickly, as from https://wimp.usersys.redhat.com/?change_id_input\u003dI24bea131cc949888518994a3aa08c200d579cb7d :\n\nrhos-17.0\nTrunk\n    192802e\n    Absent\n    16.4.1-0.20220215223418.0b6b716.el8osttrunk\n    Could not determine CI status\nRelease\n    192802e\n    Absent\n    16.4.1-0.20220215230641.0b6b716.el9ost\n    RHOS-17.0-RHEL-9-20220308.n.1\n    No zstream found\n\ntherefore we have strange behaviour in 17 gate jobs:\nimage registry-proxy.engineering.redhat.com/rh-osbs/rhceph:5-102...\", \"Non-zero exit code 125 from /bin/podman pull registry-proxy.engineering.redhat.com/rh-osbs/rhceph:5-102\", \"/bin/podman: stderr Trying to pull registry-proxy.engineering.redhat.com/rh-osbs/rhceph:5-102...\", \"/bin/podman: stderr   Get \\\"https://registry-proxy.engineering.redhat.com/v2/\\\": x509: certificate signed by unknown authority\", \"/bin/podman: stderr Error: Error initializing source docker://registry-proxy.engineering.redhat.com/rh-osbs/rhceph:5-102: error pinging docker registry registry-proxy.engineering.redhat.com: Get \\\"https://registry-proxy.engineering.redhat.com/v2/\\\": x509: certificate signed by unknown authority\", \"Traceback (most recent call last):\", \"  File \\\"/usr/sbin/cephadm\\\", line 8140, in \u003cmodule\u003e\", \"    main()\", \"  File \\\"/usr/sbin/cephadm\\\", line 8128, in main\", \"    r \u003d ctx.func(ctx)\", \"  File \\\"/usr/sbin/cephadm\\\", line 1730, in _default_image\", \"    return func(ctx)\", \"  File \\\"/usr/sbin/cephadm\\\", line 3997, in command_bootstrap\", \"    _pull_image(ctx, ctx.image)\", \"  File \\\"/usr/sbin/cephadm\\\", line 3333, in _pull_image\", \"    raise RuntimeError(\u0027Failed command: %s\u0027 % cmd_str)\", \"RuntimeError: Failed command: /bin/podman pull registry-proxy.engineering.redhat.com/rh-osbs/rhceph:5-102\"], \"stdout\": \"\", \"stdout_lines\": []}\n2022-03-12 01:50:43.481268 | 52540002-201d-6bc4-17ba-00000000006d |     TIMING | tripleo_cephadm : Run cephadm bootstrap | controller-0 | 0:00:45.819202 | 11.62s\n\nwhen OC seems to be skipping UC and trying to fetch the container from remote directly? Should not the tripleo content this was waiting on fix exactly such behaviour as tripleo should handle the UC fetching from now on?",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "d4e512db_f207e548",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2022-03-14T11:16:29Z",
      "side": 1,
      "message": "(failure log taken from http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/210/undercloud-0/home/stack/overcloud_ceph_deployment.log.gz and https://rhos-ci-jenkins.lab.eng.tlv2.redhat.com/job/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/210/)",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3920e780_3ecb06ae",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2022-03-14T11:20:20Z",
      "side": 1,
      "message": "Note also the package fix, according to LADA, should be https://brewweb.engineering.redhat.com/brew/buildinfo?buildID\u003d1899608 but https://brewweb.engineering.redhat.com/brew/buildinfo?buildID\u003d1884704 is present (http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/210/undercloud-0/var/log/extra/package-list-installed.txt.gz).\n",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c0447ad1_5832de51",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2022-03-14T11:23:49Z",
      "side": 1,
      "message": "(also same in latest build, 216, http://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/compact-gate-puddle-17.0_director-rhel-8.4-virthost-3cont_2comp_3ceph-ipv4-geneve-ceph/216/undercloud-0/var/log/extra/package-list-installed.txt.gz)",
      "revId": "128631a2c30549bda82a3555b4966bda71d36c3b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}