{
  "comments": [
    {
      "key": {
        "uuid": "55f85a92_a3b57885",
        "filename": "plugins/tripleo-undercloud/tasks/prepare_uc_images.yml",
        "patchSetId": 1
      },
      "lineNbr": 130,
      "author": {
        "id": 1009495
      },
      "writtenOn": "2020-02-20T08:49:38Z",
      "side": 0,
      "message": "Probably failing because that debug line made it past review",
      "range": {
        "startLine": 129,
        "startChar": 0,
        "endLine": 130,
        "endChar": 40
      },
      "revId": "2d49af17b164df5a008285d1ba7ac91e4923f96b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}