{
  "comments": [
    {
      "key": {
        "uuid": "8473a3a0_ea076c39",
        "filename": "plugins/tripleo-undercloud/tasks/prepare_uc_images.yml",
        "patchSetId": 2
      },
      "lineNbr": 209,
      "author": {
        "id": 1006298
      },
      "writtenOn": "2020-01-20T15:36:26Z",
      "side": 1,
      "message": "you want to not use a column here. I just got the following error:\nERROR   \u003cclass \u0027ansible.errors.AnsibleParserError\u0027\u003e: Syntax Error while loading YAML.\n  mapping values are not allowed here\n\nThe error appears to have been in \u0027/home/ospdeploy/ci/infrared/run/haa-05.ha.lab.eng.bos.redhat.com/plugins/tripleo-undercloud/tasks/prepare_uc_images.yml\u0027: line 209, column 37, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n              - name: ceph-dashboard: replace namespace\n                                    ^ here",
      "range": {
        "startLine": 209,
        "startChar": 34,
        "endLine": 209,
        "endChar": 39
      },
      "revId": "2f7863ed4e6bed0619b40caf86f975808b0ac7b1",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a099a0f9_7ddd5f22",
        "filename": "plugins/tripleo-undercloud/tasks/prepare_uc_images.yml",
        "patchSetId": 2
      },
      "lineNbr": 209,
      "author": {
        "id": 1001189
      },
      "writtenOn": "2020-01-20T15:39:50Z",
      "side": 1,
      "message": "yeah, issue in patchset 2, in ps3 i\u0027ve already wrapped them properly in \"\"",
      "parentUuid": "8473a3a0_ea076c39",
      "range": {
        "startLine": 209,
        "startChar": 34,
        "endLine": 209,
        "endChar": 39
      },
      "revId": "2f7863ed4e6bed0619b40caf86f975808b0ac7b1",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "ff466463_6ecfe3bb",
        "filename": "plugins/tripleo-undercloud/tasks/prepare_uc_images.yml",
        "patchSetId": 2
      },
      "lineNbr": 216,
      "author": {
        "id": 1006298
      },
      "writtenOn": "2020-01-20T15:36:26Z",
      "side": 1,
      "message": "same here",
      "range": {
        "startLine": 216,
        "startChar": 35,
        "endLine": 216,
        "endChar": 39
      },
      "revId": "2f7863ed4e6bed0619b40caf86f975808b0ac7b1",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}