{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "5e408f7f_83351acb",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1009328
      },
      "writtenOn": "2022-06-28T08:46:58Z",
      "side": 1,
      "message": "Please dont merge I am testing run with the revert.",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5262fef3_9b6d1d23",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1015563
      },
      "writtenOn": "2022-06-28T09:25:00Z",
      "side": 1,
      "message": "Lets figure out why your jobs are failing instead of reverting the change.\nThis change aligns the templates we use for downstream testing with what is in all examples we ship with tripleo-heat-templates.",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6142e099_b8499a5a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1003043
      },
      "writtenOn": "2022-06-28T09:26:32Z",
      "side": 1,
      "message": "This is also around the time when ipv6 pipeline and phase2 jobs started to fail.",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "a16ef61a_7da7e20f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1015563
      },
      "writtenOn": "2022-06-28T09:46:04Z",
      "side": 1,
      "message": "Can you provide logs for the failing jobs?\nreverting this change may actually hide product bugs.",
      "parentUuid": "6142e099_b8499a5a",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "4f5cfc74_ae5757e1",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1003043
      },
      "writtenOn": "2022-06-28T09:54:14Z",
      "side": 1,
      "message": "I sent you on IRC already.",
      "parentUuid": "a16ef61a_7da7e20f",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "98dc8d3e_8434af0d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1015563
      },
      "writtenOn": "2022-06-28T09:58:59Z",
      "side": 1,
      "message": "ok, thanks. I am afk, taking the kid to the doc. I\u0027ll check IRC later.",
      "parentUuid": "4f5cfc74_ae5757e1",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "a8e8db02_06edec28",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1009328
      },
      "writtenOn": "2022-06-28T10:00:47Z",
      "side": 1,
      "message": "THe patch you submitted is affecting all IPv6 deployments. \nI am testing the revert and it looks like that without your change",
      "parentUuid": "5262fef3_9b6d1d23",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "cb1f7c5d_4d4dd050",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1009328
      },
      "writtenOn": "2022-06-28T10:00:47Z",
      "side": 1,
      "message": "I am good to merge this revert and unblock IPv6 deployments. \nif any info is needed from my side please feel free to ask. \nhttps://rhos-ci-jenkins.lab.eng.tlv2.redhat.com/view/DFG/view/network/view/networking-ovn/job/DFG-network-networking-ovn-17.0_director-rhel-virthost-3cont_2comp-ipv6-geneve-dvr-rally/",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "03b863fc_ca736f4a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1015563
      },
      "writtenOn": "2022-06-28T10:05:14Z",
      "side": 1,
      "message": "I assume your IPv6 jobs are IPv4 ctlmplane and IPv6 on all isolated nets? if that is the case in barmetal_deployment.yaml you need yo set:\n  \n  default_route_networks:\n    - external\n    - ctlplane\n\n\nThis will ensure IPv4 gateway on ctlplane, and IPv6 gateway on br-ex.",
      "parentUuid": "cb1f7c5d_4d4dd050",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "04300536_86522298",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1003043
      },
      "writtenOn": "2022-06-28T10:13:20Z",
      "side": 1,
      "message": "Can send alternate to revert change ?",
      "parentUuid": "03b863fc_ca736f4a",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f0fa58c1_84ebf59b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1009328
      },
      "writtenOn": "2022-06-28T10:13:47Z",
      "side": 1,
      "message": "This is how our baremetal_deployment looks like: \n\nhttp://rhos-ci-logs.lab.eng.tlv2.redhat.com/logs/rcj/DFG-network-networking-ovn-17.0_director-rhel-virthost-3cont_2comp-ipv6-geneve-dvr-rally/29/undercloud-0/home/stack/templates/overcloud-baremetal-deployed.yaml.gz",
      "parentUuid": "03b863fc_ca736f4a",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "8cfe1fa9_c052d397",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1015563
      },
      "writtenOn": "2022-06-28T10:16:52Z",
      "side": 1,
      "message": "As mentioned in previous comment I\u0027m afk on cellular device, can\u0027t see the logs since I am not on VPN. I will check when back home this afternoon.",
      "parentUuid": "f0fa58c1_84ebf59b",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "be0bd7ad_905b8c3e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1001189
      },
      "writtenOn": "2022-06-28T10:34:05Z",
      "side": 1,
      "message": "Unless there is very fast fix for all affected jobs, I\u0027m for immediate revert (and reproposing when fixed), as otherwise this needs to be CIXed.",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e1d9db2c_dd493da8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1001189
      },
      "writtenOn": "2022-06-28T10:42:45Z",
      "side": 1,
      "message": "FYI, the exact error appears more like syntax issue, example from phase2 jobs:\n\n  FATAL | Run tripleo_os_net_config_module with network_config | controller-0 | error\u003d{\\\"ansible_job_id\\\": \\\"814357656218.2140\\\", \\\"changed\\\": false, \\\"finished\\\": 1, \\\"msg\\\": \\\"Running os-net-config --config-file /etc/os-net-config/config.yaml --debug --detailed-exit-codes failed with return code 1.\\\", \\\"rc\\\": 1, \\\"results_file\\\": \\\"/root/.ansible_async/814357656218.2140\\\", \\\"started\\\": 1, \\\"stderr\\\": \\\"Traceback (most recent call last):\\\n    File \\\\\\\"/bin/os-net-config\\\\\\\", line 10, in \u003cmodule\u003e\\\n      sys.exit(main())\\\n    File \\\\\\\"/usr/lib/python3.9/site-packages/os_net_config/cli.py\\\\\\\", line 245, in main\\\n      iface_array \u003d yaml.safe_load(cf.read()).get(\\\\\\\"network_config\\\\\\\")\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/__init__.py\\\\\\\", line 162, in safe_load\\\n      return load(stream, SafeLoader)\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/__init__.py\\\\\\\", line 114, in load\\\n      return loader.get_single_data()\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/constructor.py\\\\\\\", line 49, in get_single_data\\\n      node \u003d self.get_single_node()\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/composer.py\\\\\\\", line 36, in get_single_node\\\n      document \u003d self.compose_document()\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/composer.py\\\\\\\", line 55, in compose_document\\\n      node \u003d self.compose_node(None, None)\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/composer.py\\\\\\\", line 84, in compose_node\\\n      node \u003d self.compose_mapping_node(anchor)\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/composer.py\\\\\\\", line 133, in compose_mapping_node\\\n      item_value \u003d self.compose_node(node, item_key)\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/composer.py\\\\\\\", line 82, in compose_node\\\n      node \u003d self.compose_sequence_node(anchor)\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/composer.py\\\\\\\", line 111, in compose_sequence_node\\\n      node.value.append(self.compose_node(node, index))\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/composer.py\\\\\\\", line 84, in compose_node\\\n      node \u003d self.compose_mapping_node(anchor)\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/composer.py\\\\\\\", line 127, in compose_mapping_node\\\n      while not self.check_event(MappingEndEvent):\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/parser.py\\\\\\\", line 98, in check_event\\\n      self.current_event \u003d self.state()\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/parser.py\\\\\\\", line 428, in parse_block_mapping_key\\\n      if self.check_token(KeyToken):\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/scanner.py\\\\\\\", line 116, in check_token\\\n      self.fetch_more_tokens()\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/scanner.py\\\\\\\", line 223, in fetch_more_tokens\\\n      return self.fetch_value()\\\n    File \\\\\\\"/usr/lib64/python3.9/site-packages/yaml/scanner.py\\\\\\\", line 577, in fetch_value\\\n      raise ScannerError(None, None,\\\n  yaml.scanner.ScannerError: mapping values are not allowed here\\\n    in \\\\\\\"\u003cunicode string\u003e\\\\\\\", line 46, column 17:\\\n        routes: routes: [{\u0027default\u0027: True, \u0027nexthop\u0027:  ... \\\n                      ^\\",
      "revId": "83d6e51ca985588c46612bb486df774fc32151fb",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ],
  "submitRequirementResults": []
}